### PR TITLE
Release 1.0.5

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 1.0.5
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by Hlavtox** [comment]
@kpodemski Add Waiting for QA pls, and permissions fix

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@sallemiines Fixed, check again please. 🙏

**Review by djoelleuch — APPROVED** [review]
Hello @Hlavtox ! 

It's QA :heavy_check_mark:  

pr1

https://user-images.githubusercontent.com/115152460/212653871-72d8c783-a324-4732-ad18-2336fc459e9a.mp4




Thanks for your PR :rocket:

**Comment by Hlavtox** [comment]
Thank you @sallemiines & @djoelleuch! 🎉🌷

**Pull request merged**
