### PR TITLE
Wrong cache key used in ps_categoryproducts

### PR DESCRIPTION
**Pull request by Matt75**
This pull request fix an issue with cache key
https://github.com/PrestaShop/PrestaShop/issues/9652

### CODE REVIEW

**Comment by ComonSoft** [comment]
Other issues concerned [BOOM-3810](http://forge.prestashop.com/browse/BOOM-3810) . The pull request fix also the issue in multistore mode

**Comment by Matt75** [comment]
Ping @Quetzacoalt91 @eternoendless 😎

**Comment by Quetzacoalt91** [comment]
Fine by me. This call adds context details such as the current language / currency / shop / customer group...

**Comment by Quetzacoalt91** [comment]
Thank you @Matt75

**Pull request merged**
