### PR TITLE
Release version 1.0.6

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Releases version 1.0.6 to fix version mismatch which can cause upgrade problems. Does not need QA and can be merged immediately.
| Type?         | critical
| BC breaks?    |
| Deprecations? |
| Fixed ticket? |
| How to test?  |

### CODE REVIEW

**Comment by Peter26100** [comment]
Since the update of module 1.6, the description of the module is no longer displayed, as well as the price, just on the first product (prestashop 1.7.8.6)

* screenshot
Capture55

**Comment by Hlavtox** [comment]
@Peter26100 This is nothing to do with this release, it only changed the version number. It's an issue on your shop.

**Comment by Peter26100** [comment]
I just clicked on module update in Prestashop, and now it doesn't work anymore... whereas it worked very well before

**Comment by SharakPL** [comment]
@Peter26100 did you have changes in module files before the update? They would have been replaced by the update. If you want to change modules behaviour to fit your theme then you should make a proper override. Never change modules directly in /modules directory.

Anyway this looks like a misconfiguration in your theme's module files.

**Pull request merged**
